// string must be unique

const MOVIE_DATA_ACTION_TYPES = {
  ADD_MOVIE_DATA_GLOBAL_STATE: "ADD_MOVIE_DATA_GLOBAL_STATE",
  DELETE_MOVIE_DATA_GLOBAL_STATE: "DELETE_MOVIE_DATA_GLOBAL_STATE",
};

export default MOVIE_DATA_ACTION_TYPES;
