// string must be unique
const DATA_ACTION_TYPES = {
  ADD_DATA_GLOBAL_STATE: "ADD_DATA_GLOBAL_STATE",
  DELETE_DATA_GLOBAL_STATE: "DELETE_DATA_GLOBAL_STATE",
  DELETE_ALL_DATA_GLOBAL_STATE: "DELETE_ALL_DATA_GLOBAL_STATE",
};
export default DATA_ACTION_TYPES;
