// string must be unique
const XML_DATA_ACTION_TYPES = {
  ADD_XML_DATA_GLOBAL_STATE: "ADD_XML_DATA_GLOBAL_STATE",
  DELETE_XML_DATA_GLOBAL_STATE: "DELETE_XML_DATA_GLOBAL_STATE",
};

export default XML_DATA_ACTION_TYPES;
